# -*- coding: utf-8 -*-
"""IsPalindrome.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_DWQqN818ao1CHOY_ydc6eCMX_w7qLQg
"""

# check if input string is palindrome or not
def ispalindrome(str):

    str="".join(char.lower() for char in str if char.isalnum())
    if(str[::]==str[::-1]):
        return True
    else:
        return False

def main():
    input_str=input("Please enter sentence or word: ")
    if(ispalindrome(input_str)):
        print(f"{input_str} is a palindrome")
    else:
        print(f"{input_str} is not a palindrome")

if __name__=="__main__":
    main()

